name: CI

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  eslint:
    name: Lint Code
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install modules
        run: bun install --frozen-lockfile
      - name: Run ESLint
        run: bun lint
